package com.icona.gui;
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

import java.util.ArrayList;

import com.icona.helper.DBDataPopulator;
import com.icona.helper.DBDataStorer;
import com.icona.helper.DAO.ClassDAO;
import com.icona.helper.DAO.FunctionDAO;
import com.icona.helper.DAO.Language;

/**
 *
 * @author Gulraiz
 */
public class ApiMap extends javax.swing.JPanel {

    

    /**
     * Creates new form NewJPanel
     */
    public ApiMap() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {
    	
    	dbstor=new DBDataStorer();
        dbpop=new DBDataPopulator();
        objcClasses=dbpop.getAllClasses(Language.OBJC);
    	javaClasses=dbpop.getAllClasses(Language.JAVA);
    	
    	
        classButton = new javax.swing.JButton();
        functionButton = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jSplitPane1 = new javax.swing.JSplitPane();
        objectivecClassPanel = new javax.swing.JPanel();
        classNameLabel = new javax.swing.JLabel();
        objCclassNametextfield = new javax.swing.JTextField();
        superClassNameLabel = new javax.swing.JLabel();
        objCsuperclassdropdown = new javax.swing.JComboBox();
        objectiveclabel = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        javalabel = new javax.swing.JLabel();
        javaclassnamelabel = new javax.swing.JLabel();
        javaclassNametextfield = new javax.swing.JTextField();
        javasupperclasslabel = new javax.swing.JLabel();
        javasuperclassdropdown = new javax.swing.JComboBox();
        javaimportlabel = new javax.swing.JLabel();
        javaclassimport = new javax.swing.JTextField();
        jSplitPane2 = new javax.swing.JSplitPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        objectivecfunctionnamelabel = new javax.swing.JLabel();
        cfunctionNameInput = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cFunctionReturn = new javax.swing.JTextField();
        cFunctionClassList = new javax.swing.JComboBox();
        jPanel3 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        objectivecfunctionnamelabel2 = new javax.swing.JLabel();
        javafunctionNameInput1 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        javaFunctionReturn1 = new javax.swing.JTextField();
        javaFunctionClassList1 = new javax.swing.JComboBox();
        SubmitButton = new javax.swing.JToggleButton();

        classButton.setBackground(new java.awt.Color(255, 240, 240));
        classButton.setText("Class");
        classButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                classButtonMouseClicked(evt);
            }
        });

        functionButton.setText("Function");
        functionButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                functionButtonMouseClicked(evt);
            }
        });
        functionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                functionButtonActionPerformed(evt);
            }
        });

        classNameLabel.setText("Class Name");

        superClassNameLabel.setText("Supper Class");

       
        objectiveclabel.setText("Objective C Class");

        
        
        
        
        
        
        if(objcClasses!=null)
        {
	        System.out.print(objcClasses.size());
	        String [] allnames=new String[objcClasses.size()];
	        
	        for (int i=0; i<objcClasses.size(); i++)
	        {
	        	allnames[i]=objcClasses.get(i).getClassName();
	        	
	        }
	        objCsuperclassdropdown.setModel(new javax.swing.DefaultComboBoxModel(allnames));
        }
        else
        	objCsuperclassdropdown.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "None" }));
        
        
        
        
        
        javax.swing.GroupLayout objectivecClassPanelLayout = new javax.swing.GroupLayout(objectivecClassPanel);
        objectivecClassPanel.setLayout(objectivecClassPanelLayout);
        objectivecClassPanelLayout.setHorizontalGroup(
            objectivecClassPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(objectivecClassPanelLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(objectivecClassPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(objectivecClassPanelLayout.createSequentialGroup()
                        .addComponent(superClassNameLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(objCsuperclassdropdown, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(objectiveclabel)
                    .addGroup(objectivecClassPanelLayout.createSequentialGroup()
                        .addComponent(classNameLabel)
                        .addGap(18, 18, 18)
                        .addComponent(objCclassNametextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        objectivecClassPanelLayout.setVerticalGroup(
            objectivecClassPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, objectivecClassPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(objectiveclabel)
                .addGap(25, 25, 25)
                .addGroup(objectivecClassPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(classNameLabel)
                    .addComponent(objCclassNametextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(objectivecClassPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(objCsuperclassdropdown, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(superClassNameLabel))
                .addContainerGap(44, Short.MAX_VALUE))
        );

        jSplitPane1.setLeftComponent(objectivecClassPanel);

        javalabel.setText("Java Class");

        javaclassnamelabel.setText("Class Name");

        javasupperclasslabel.setText("Supper Class");

        
        
        
        if(javaClasses!=null)
        {
	        System.out.print(javaClasses.size());
	        String [] allnames=new String[javaClasses.size()];
	        
	        for (int i=0; i<javaClasses.size(); i++)
	        {
	        	allnames[i]=javaClasses.get(i).getClassName();
	        	
	        }
	        javasuperclassdropdown.setModel(new javax.swing.DefaultComboBoxModel(allnames));
        }
        else
        	javasuperclassdropdown.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "None" }));
        
        
        
        
        
       
        javaimportlabel.setText("Import");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(javalabel)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(javaclassnamelabel)
                        .addGap(18, 18, 18)
                        .addComponent(javaclassNametextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(javasupperclasslabel)
                            .addComponent(javaimportlabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(javaclassimport, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(javasuperclassdropdown, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(111, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(javalabel)
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(javaclassnamelabel)
                    .addComponent(javaclassNametextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(javasupperclasslabel)
                    .addComponent(javasuperclassdropdown, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(javaclassimport, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(javaimportlabel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jSplitPane1.setRightComponent(jPanel1);

        jLabel1.setText("Objectve C Function");

        objectivecfunctionnamelabel.setText("Function Name");

        cfunctionNameInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cfunctionNameInputActionPerformed(evt);
            }
        });

        jLabel3.setText("Class");

        jLabel4.setText("Return Type");

        
        
        if(objcClasses!=null)
        {
	        System.out.print(objcClasses.size());
	        String [] allnames=new String[objcClasses.size()];
	        
	        for (int i=0; i<objcClasses.size(); i++)
	        {
	        	allnames[i]=objcClasses.get(i).getClassName();
	        	
	        }
	        cFunctionClassList.setModel(new javax.swing.DefaultComboBoxModel(allnames));
        }
        else
        	cFunctionClassList.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "None" }));
        
        
           
        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(objectivecfunctionnamelabel)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cfunctionNameInput)
                            .addComponent(cFunctionReturn)
                            .addComponent(cFunctionClassList, 0, 240, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(objectivecfunctionnamelabel)
                    .addComponent(cfunctionNameInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(cFunctionClassList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(cFunctionReturn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(51, Short.MAX_VALUE))
        );

        jSplitPane2.setLeftComponent(jPanel2);

        jLabel7.setText("Java Function");

        objectivecfunctionnamelabel2.setText("Function Name");

        javafunctionNameInput1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                javafunctionNameInputActionPerformed(evt);
            }
        });

        jLabel8.setText("Class");

        jLabel9.setText("Return Type");

        
        
        if(javaClasses!=null)
        {
	        System.out.print(javaClasses.size());
	        String [] allnames=new String[javaClasses.size()];
	        
	        for (int i=0; i<javaClasses.size(); i++)
	        {
	        	allnames[i]=javaClasses.get(i).getClassName();
	        	
	        }
	        javaFunctionClassList1.setModel(new javax.swing.DefaultComboBoxModel(allnames));
        }
        else
        	javaFunctionClassList1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "None" }));
        
        
        

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(objectivecfunctionnamelabel2)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(javafunctionNameInput1)
                            .addComponent(javaFunctionReturn1)
                            .addComponent(javaFunctionClassList1, 0, 158, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(objectivecfunctionnamelabel2)
                    .addComponent(javafunctionNameInput1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(javaFunctionClassList1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel9)
                    .addComponent(javaFunctionReturn1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(51, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jSplitPane2.setRightComponent(jPanel3);

        SubmitButton.setText("Submit");
        SubmitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSplitPane1)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jSplitPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(SubmitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(259, 259, 259))))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSplitPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jSplitPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SubmitButton)
                .addGap(184, 184, 184))
        );

        jSplitPane2.setVisible(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(classButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(functionButton))
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(classButton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(functionButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 403, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>

    private void classButtonMouseClicked(java.awt.event.MouseEvent evt) {
        this.jSplitPane1.setVisible(true);
        this.jSplitPane2.setVisible(false);
    }

    private void SubmitButtonActionPerformed(java.awt.event.ActionEvent evt) {
    	ClassDAO objcClass;
    	ClassDAO javaClass;
    	
    	FunctionDAO objcFunc;
    	FunctionDAO javaFunc;
    	if(jSplitPane1.isVisible())
    	{	
    		objcClass=new ClassDAO(0,objCclassNametextfield.getText(), getClassIdobjc(objCsuperclassdropdown.getSelectedItem().toString()),"","",Language.OBJC,"" );
    		dbstor.insertClass(objcClass);
    		
    		javaClass=new ClassDAO(0,javaclassNametextfield.getText(), getClassIdjava(javasuperclassdropdown.getSelectedItem().toString()),"","",Language.OBJC,javaclassimport.getText() );
    		dbstor.insertClass(objcClass);
    		// Add mapping to mapping Table
    	}
    	else if(jSplitPane2.isVisible())
    	{	
    		objcFunc=new FunctionDAO(0,getClassIdobjc(cFunctionClassList.getSelectedItem().toString()),cfunctionNameInput.getText(),0,cFunctionReturn.getText(),"","","" );
    		dbstor.insertFunction(objcFunc);
    		
    		javaFunc=new FunctionDAO(0,getClassIdjava(javaFunctionClassList1.getSelectedItem().toString()),javafunctionNameInput1.getText(),0,javaFunctionReturn1.getText(),"","","" );
    		dbstor.insertFunction(javaFunc);
    		
    		// Add mapping to mapping Table
    	}
    }

    private void functionButtonActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        
    }

    private void functionButtonMouseClicked(java.awt.event.MouseEvent evt) {
      this.jSplitPane2.setVisible(true);
      this.jSplitPane1.setVisible(false);
        // TODO add your handling code here:
    }

    private void cfunctionNameInputActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void javafunctionNameInputActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    public int getClassIdobjc(String name)
    {
    	for(int i=0; i<objcClasses.size(); i++)
    		if(objcClasses.get(i).getClassName()==name)
    			return objcClasses.get(i).getClassId();
    	return -1;
    }
    public int getClassIdjava(String name)
    {
    	for(int i=0; i<javaClasses.size(); i++)
    		if(javaClasses.get(i).getClassName()==name)
    			return javaClasses.get(i).getClassId();
    	
    	return -1;
    }
    
    // Variables declaration - do not modify
    private javax.swing.JToggleButton SubmitButton;
    private javax.swing.JComboBox cFunctionClassList;
    private javax.swing.JTextField cFunctionReturn;
    private javax.swing.JTextField cfunctionNameInput;
    private javax.swing.JButton classButton;
    private javax.swing.JLabel classNameLabel;
    private javax.swing.JButton functionButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JSplitPane jSplitPane2;
 
    private javax.swing.JComboBox javaFunctionClassList1;
  
    private javax.swing.JTextField javaFunctionReturn1;
    private javax.swing.JTextField javaclassNametextfield;
    private javax.swing.JTextField javaclassimport;
    private javax.swing.JLabel javaclassnamelabel;
   
    private javax.swing.JTextField javafunctionNameInput1;
    private javax.swing.JLabel javaimportlabel;
    private javax.swing.JLabel javalabel;
    private javax.swing.JComboBox javasuperclassdropdown;
    private javax.swing.JLabel javasupperclasslabel;
    private javax.swing.JTextField objCclassNametextfield;
    private javax.swing.JComboBox objCsuperclassdropdown;
    private javax.swing.JPanel objectivecClassPanel;
    private javax.swing.JLabel objectivecfunctionnamelabel;
    private javax.swing.JLabel objectivecfunctionnamelabel1;
    private javax.swing.JLabel objectivecfunctionnamelabel2;
    private javax.swing.JLabel objectiveclabel;
    private javax.swing.JLabel superClassNameLabel;
    private ArrayList<ClassDAO> objcClasses;
    private ArrayList<ClassDAO> javaClasses;
    private DBDataPopulator dbpop;
    private DBDataStorer dbstor;
    // End of variables declaration
}
